name: dean-server
services:
  # Base verdaccio service, extended into live and dev versions in docker-compose.yml
  verdaccio:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      - LATEST_ENV=1.2.0
      - ENV_VERSION=${ENV_VERSION:?Environment file not up to date}