services:
  verdaccio:
    extends: 
      file: compose.verdaccio.yml
      service: verdaccio
    profiles:
      - live
    image: jackdeaniels/private:verdaccio-latest
    container_name: verdaccio
    ports:
      - ${VERDACCIO_PORT:-4873}:4873
    volumes:
      - ./mounts/live/conf:/verdaccio/conf:ro
      - ${VERDACCIO_STORAGE:-./mounts/live/storage}:/verdaccio/storage
      - ${VERDACCIO_CERTS:-./mounts/live/certs}:/verdaccio/certs:ro
    environment:
      # - DOMAIN=${VERDACCIO_DOMAIN}
      - DOMAIN=${VERDACCIO_DOMAIN:?}
      - HOST_PORT=${VERDACCIO_PORT:-4873}
      - PROXY_PORT=${VERDACCIO_PROXY_PORT:-${VERDACCIO_PORT:-4873}}
      
  verdaccio-dev:
    extends: 
      file: compose.verdaccio.yml
      service: verdaccio
    profiles:
      - dev
    image: jackdeaniels/private:verdaccio-dev
    develop:
      watch:
        - action: rebuild
          path: ./files
          target: /verdaccio
    container_name: verdaccio-dev
    ports:
      - ${VERDACCIO_DEV_PORT:-${VERDACCIO_PORT:-4873}}:4873
    volumes:
      - ./mounts/${VERDACCIO_DEV_CONF:-live}/conf:/verdaccio/conf:ro
      - ${VERDACCIO_DEV_STORAGE:-${VERDACCIO_STORAGE:-./mounts/dev/storage}}:/verdaccio/storage
      - ${VERDACCIO_DEV_CERTS:-${VERDACCIO_CERTS:-./mounts/dev/certs}}:/verdaccio/certs:ro
    environment:
      - DOMAIN=${VERDACCIO_DEV_DOMAIN:-${VERDACCIO_DOMAIN:?}}
      - HOST_PORT=${VERDACCIO_DEV_PORT:-${VERDACCIO_PORT:-4873}}
      - PROXY_PORT=${VERDACCIO_PROXY_PORT:-${VERDACCIO_DEV_PORT:-${VERDACCIO_PORT:-4873}}}