services:
  verdaccio:
    extends: 
      file: compose.base.yml
      service: verdaccio
    profiles:
      - live
    image: jackdeaniels/private:verdaccio-latest
    container_name: verdaccio
    volumes:
      - ./mounts/live/conf:/verdaccio/conf:ro
      - ${STORAGE:-./mounts/live/storage}:/verdaccio/storage
      - ${LOGS:-./mounts/live/logs}:/verdaccio/logs
    environment:
      - DOMAIN=${DOMAIN:?}
      - HOST_PORT=${HOST_PORT:-4873}
      - PROXY_PORT=${PROXY_PORT:-${HOST_PORT:-4873}}
      - VIRTUAL_HOST=${DOMAIN:?} 
      
  verdaccio-dev:
    extends: 
      file: compose.dev.yml
      service: verdaccio-dev
    image: jackdeaniels/private:verdaccio-dev
    container_name: verdaccio-dev
    profiles:
      - dev

  verdaccio-beta:
    extends: 
      file: compose.dev.yml
      service: verdaccio-dev
    image: jackdeaniels/private:verdaccio-beta
    container_name: verdaccio-beta
    profiles:
      - beta
    build:
      dockerfile: dockerfile.beta


  # Old configuration - Uses nginx-v1
  verdaccio-v1:
    extends: 
      file: compose.base.yml
      service: verdaccio
    profiles:
      - v1
    image: jackdeaniels/private:verdaccio-v1
    container_name: verdaccio-v1
    ports:
      - ${HOST_PORT:-4873}:4873
    volumes:
      - ./mounts/v1/conf:/verdaccio/conf:ro
      - ${STORAGE:-./mounts/live/storage}:/verdaccio/storage
      - ${CERTS:-./mounts/live/certs}:/verdaccio/certs:ro
    environment:
      - VERDACCIO_PROTOCOL=https
      - DOMAIN=${DOMAIN:?}
      - HOST_PORT=${HOST_PORT:-4873}
      - PROXY_PORT=${PROXY_PORT:-${HOST_PORT:-4873}}
      
