services:
  verdaccio:
    extends: 
      file: compose.base.yml
      service: verdaccio
    profiles:
      - live
    image: jackdeaniels/private:verdaccio-latest
    container_name: verdaccio
    volumes:
      - ./mounts/live/conf:/verdaccio/conf:ro
      - ${STORAGE:-./mounts/live/storage}:/verdaccio/storage
      - ${LOGS:-./mounts/live/logs}:/verdaccio/logs
    environment:
      - DOMAIN=${DOMAIN:?}
      - HOST_PORT=${HOST_PORT:-4873}
      - PROXY_PORT=${PROXY_PORT:-${HOST_PORT:-4873}}
      - VIRTUAL_HOST=${DOMAIN:?} 
      
  verdaccio-dev:
    extends: 
      file: compose.dev.yml
      service: verdaccio-dev
    image: jackdeaniels/private:verdaccio-dev
    container_name: verdaccio-dev
    profiles:
      - dev

  # Uses the beta version of Verdaccio - No errors were observed
  verdaccio-beta:
    extends: 
      file: compose.dev.yml
      service: verdaccio-dev
    image: jackdeaniels/private:verdaccio-beta
    container_name: verdaccio-beta
    profiles:
      - beta
    build:
      dockerfile: dockerfile.beta