services:
  # Base verdaccio service, extended into live and dev versions in docker-compose.yml
  verdaccio:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      - VERDACCIO_PROTOCOL=https
      - LATEST_ENV=1.0
      - VERDACCIO_ENV=${VERDACCIO_ENV:?Environment file not up to date}