services:
  verdaccio:
    profiles: []
    build:
      dockerfile: dockerfile
    develop:
      watch:
        - action: rebuild
          path: ./files
          target: /verdaccio
    environment:
      - VERDACCIO_PROTOCOL=https
      - LATEST_ENV=0.9
      - VERDACCIO_ENV=${VERDACCIO_ENV:?Environment file not up to date}

  verdaccio-live:
    extends: verdaccio
    profiles:
      - live
    image: jackdeaniels/private:verdaccio-latest
    container_name: verdaccio
    ports:
      - ${VERDACCIO_PORT:-4873}:4873
    volumes:
      - ${VERDACCIO_STORAGE:-./mounts/storage}:/verdaccio/storage
      - ${VERDACCIO_CERTS:-./mounts/certs}:/verdaccio/certs:ro
    environment:
      # - DOMAIN=${VERDACCIO_DOMAIN}
      - DOMAIN=${VERDACCIO_DOMAIN:?}
      - HOST_PORT=${VERDACCIO_PORT:-4873}
      - PROXY_PORT=${VERDACCIO_PROXY_PORT:-${VERDACCIO_PORT:-4873}}
      
  verdaccio-dev:
    extends: verdaccio
    profiles:
      - dev
    image: jackdeaniels/private:verdaccio-dev
    container_name: verdaccio-dev
    ports:
      - ${VERDACCIO_DEV_PORT:-${VERDACCIO_PORT:-4873}}:4873
    volumes:
      - ${VERDACCIO_DEV_STORAGE:-${VERDACCIO_STORAGE:-./mounts/storage}}:/verdaccio/storage
      - ${VERDACCIO_DEV_CERTS:-${VERDACCIO_CERTS:-./mounts/certs}}:/verdaccio/certs:ro
    environment:
      - DOMAIN=${VERDACCIO_DEV_DOMAIN:-${VERDACCIO_DOMAIN:?}}
      - HOST_PORT=${VERDACCIO_DEV_PORT:-${VERDACCIO_PORT:-4873}}
      - PROXY_PORT=${VERDACCIO_PROXY_PORT:-${VERDACCIO_DEV_PORT:-${VERDACCIO_PORT:-4873}}}
    