name: ${PROJECT} 
services:
  verdaccio:
    build:
      dockerfile: dockerfile
    develop:
      watch:
        - action: rebuild
          path: ./files
          target: /verdaccio
    image: ${IMAGE}:${VERSION}
    container_name: ${CONTAINER}
    environment:
      - VERDACCIO_PROTOCOL=https
      - DOMAIN=${DOMAIN}
      - HOST_PORT=${PORT:-4873}
      - PROXY_PORT=${PROXY_PORT:-${PORT:-4873}}
    ports:
      - ${PORT:-4873}:4873
    volumes:
      - ${STORAGE}:/verdaccio/storage
      - ${CERTS}:/verdaccio/certs:ro